# coding: utf-8

"""
    OrderCloud

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    Contact: ordercloud@four51.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class PartialIncrementor(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, name=None, last_number=None, left_padding_count=None):
        """
        PartialIncrementor - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'name': 'str',
            'last_number': 'int',
            'left_padding_count': 'int'
        }

        self.attribute_map = {
            'id': 'ID',
            'name': 'Name',
            'last_number': 'LastNumber',
            'left_padding_count': 'LeftPaddingCount'
        }

        self._id = id
        self._name = name
        self._last_number = last_number
        self._left_padding_count = left_padding_count

    @property
    def id(self):
        """
        Gets the id of this PartialIncrementor.


        :return: The id of this PartialIncrementor.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PartialIncrementor.


        :param id: The id of this PartialIncrementor.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this PartialIncrementor.


        :return: The name of this PartialIncrementor.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PartialIncrementor.


        :param name: The name of this PartialIncrementor.
        :type: str
        """

        self._name = name

    @property
    def last_number(self):
        """
        Gets the last_number of this PartialIncrementor.


        :return: The last_number of this PartialIncrementor.
        :rtype: int
        """
        return self._last_number

    @last_number.setter
    def last_number(self, last_number):
        """
        Sets the last_number of this PartialIncrementor.


        :param last_number: The last_number of this PartialIncrementor.
        :type: int
        """

        self._last_number = last_number

    @property
    def left_padding_count(self):
        """
        Gets the left_padding_count of this PartialIncrementor.


        :return: The left_padding_count of this PartialIncrementor.
        :rtype: int
        """
        return self._left_padding_count

    @left_padding_count.setter
    def left_padding_count(self, left_padding_count):
        """
        Sets the left_padding_count of this PartialIncrementor.


        :param left_padding_count: The left_padding_count of this PartialIncrementor.
        :type: int
        """

        self._left_padding_count = left_padding_count

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
